export const languages = {
  'en-GB': {
    name: 'English (UK)',
    boot: {
      bios: 'PRIVATE WRITER BIOS v2.4',
      copyright: 'Copyright (C) 2026 Private Writer Systems',
      init: 'Initialising system...',
      kernel: 'Loading kernel... OK',
      fs: 'Mounting file systems... OK',
      processor: 'Starting text processor... OK',
      storage: 'Checking storage... OK',
      network: 'Network interface ready... OK',
      ready: 'System ready. Press any key to continue.',
    },
    menu: {
      file: 'FILE',
      edit: 'EDIT',
      view: 'VIEW',
      network: 'NETWORK',
      storage: 'STORAGE',
      power: 'POWER',
      language: 'LANGUAGE',
      settings: 'SETTINGS',
      music: 'MUSIC',
    },
    file: { new: 'New', open: 'Open', recent: 'Open Recent', save: 'Save', saveas: 'Save As' },
    edit: { undo: 'Undo', redo: 'Redo', copy: 'Copy', paste: 'Paste', selectfont: 'Select Font' },
    view: { increase: 'Increase Text Size', decrease: 'Decrease Text Size', customise: 'Customise Colours' },
    network: { wifi: 'Wi-Fi:', bluetooth: 'Bluetooth:', on: 'ON', off: 'OFF' },
    storage: { local: 'Local Storage', usb: 'USB Drive (simulated)', dropbox: '☁ Dropbox', gdrive: '☁ Google Drive', icloud: '☁ iCloud' },
    power: { update: 'Software Update', shutdown: 'Restart' },
    language: { select: 'Select Language', englishGB: 'English (UK)', englishUS: 'English (US)', afrikaans: 'Afrikaans' },
    status: { untitled: 'UNTITLED.TXT', saved: 'SAVED', words: 'WORDS', chars: 'CHARS', battery: 'BATTERY:' },
    modals: {
      saveTitle: 'SAVE DOCUMENT', savePrompt: 'Enter filename...', saveButton: 'SAVE',
      openTitle: 'OPEN DOCUMENT', recentTitle: 'RECENT DOCUMENTS',
      newTitle: 'NEW DOCUMENT', newMessage1: 'Current document has unsaved changes.', newMessage2: 'Save before creating new document?',
      saveAndNew: 'SAVE & NEW', discard: 'DISCARD', cancel: 'CANCEL',
      noFiles: 'NO SAVED DOCUMENTS', noRecent: 'NO RECENT DOCUMENTS',
      colorsTitle: 'CUSTOMISE COLOURS', textColor: 'TEXT COLOUR:', textPresets: 'PRESET TEXT COLOURS:',
      bgColor: 'BACKGROUND:', bgPresets: 'PRESET BACKGROUNDS:', apply: 'APPLY', reset: 'RESET TO DEFAULT',
      languageTitle: 'SELECT LANGUAGE',
    },
    help: { line1: 'Press ESC to open menu', line2: 'Ctrl+S to save | Ctrl+N for new file', line3: 'Ctrl+Z/R for undo/redo' },
    placeholder: 'Press any key to begin writing...',
    shutdownConfirm: 'Restart Private Writer?',
    pin: {
      setupTitle: 'SET UP PIN LOCK',
      setupDesc: 'Protect your writing with a PIN code',
      choose4: '4-DIGIT PIN',
      choose6: '6-DIGIT PIN',
      enterPin: 'Enter PIN:',
      confirmPin: 'Confirm PIN:',
      mismatch: 'PINs do not match. Try again.',
      set: 'SET PIN',
      skip: 'SKIP',
      lockTitle: 'PRIVATE WRITER LOCKED',
      lockDesc: 'Enter your PIN to unlock',
      unlock: 'UNLOCK',
      incorrect: 'Incorrect PIN. Try again.',
      remove: 'Remove PIN Lock',
    },
  },
  'en-US': {
    name: 'English (US)',
    boot: {
      bios: 'PRIVATE WRITER BIOS v2.4',
      copyright: 'Copyright (C) 2026 Private Writer Systems',
      init: 'Initializing system...',
      kernel: 'Loading kernel... OK',
      fs: 'Mounting file systems... OK',
      processor: 'Starting text processor... OK',
      storage: 'Checking storage... OK',
      network: 'Network interface ready... OK',
      ready: 'System ready. Press any key to continue.',
    },
    menu: {
      file: 'FILE',
      edit: 'EDIT',
      view: 'VIEW',
      network: 'NETWORK',
      storage: 'STORAGE',
      power: 'POWER',
      language: 'LANGUAGE',
      settings: 'SETTINGS',
      music: 'MUSIC',
    },
    file: { new: 'New', open: 'Open', recent: 'Open Recent', save: 'Save', saveas: 'Save As' },
    edit: { undo: 'Undo', redo: 'Redo', copy: 'Copy', paste: 'Paste', selectfont: 'Select Font' },
    view: { increase: 'Increase Text Size', decrease: 'Decrease Text Size', customise: 'Customize Colors' },
    network: { wifi: 'Wi-Fi:', bluetooth: 'Bluetooth:', on: 'ON', off: 'OFF' },
    storage: { local: 'Local Storage', usb: 'USB Drive (simulated)', dropbox: '☁ Dropbox', gdrive: '☁ Google Drive', icloud: '☁ iCloud' },
    power: { update: 'Software Update', shutdown: 'Restart' },
    language: { select: 'Select Language', englishGB: 'English (UK)', englishUS: 'English (US)', afrikaans: 'Afrikaans' },
    status: { untitled: 'UNTITLED.TXT', saved: 'SAVED', words: 'WORDS', chars: 'CHARS', battery: 'BATTERY:' },
    modals: {
      saveTitle: 'SAVE DOCUMENT', savePrompt: 'Enter filename...', saveButton: 'SAVE',
      openTitle: 'OPEN DOCUMENT', recentTitle: 'RECENT DOCUMENTS',
      newTitle: 'NEW DOCUMENT', newMessage1: 'Current document has unsaved changes.', newMessage2: 'Save before creating new document?',
      saveAndNew: 'SAVE & NEW', discard: 'DISCARD', cancel: 'CANCEL',
      noFiles: 'NO SAVED DOCUMENTS', noRecent: 'NO RECENT DOCUMENTS',
      colorsTitle: 'CUSTOMIZE COLORS', textColor: 'TEXT COLOR:', textPresets: 'PRESET TEXT COLORS:',
      bgColor: 'BACKGROUND:', bgPresets: 'PRESET BACKGROUNDS:', apply: 'APPLY', reset: 'RESET TO DEFAULT',
      languageTitle: 'SELECT LANGUAGE',
    },
    help: { line1: 'Press ESC to open menu', line2: 'Ctrl+S to save | Ctrl+N for new file', line3: 'Ctrl+Z/R for undo/redo' },
    placeholder: 'Press any key to begin writing...',
    shutdownConfirm: 'Restart Private Writer?',
    pin: {
      setupTitle: 'SET UP PIN LOCK',
      setupDesc: 'Protect your writing with a PIN code',
      choose4: '4-DIGIT PIN',
      choose6: '6-DIGIT PIN',
      enterPin: 'Enter PIN:',
      confirmPin: 'Confirm PIN:',
      mismatch: 'PINs do not match. Try again.',
      set: 'SET PIN',
      skip: 'SKIP',
      lockTitle: 'PRIVATE WRITER LOCKED',
      lockDesc: 'Enter your PIN to unlock',
      unlock: 'UNLOCK',
      incorrect: 'Incorrect PIN. Try again.',
      remove: 'Remove PIN Lock',
    },
  },
  'af': {
    name: 'Afrikaans',
    boot: {
      bios: 'PRIVATE WRITER BIOS v2.4',
      copyright: 'Kopiereg (C) 2026 Private Writer Stelsels',
      init: 'Stelsel word geïnisialiseer...',
      kernel: 'Laai kern... OK',
      fs: 'Monteer lêerstelsels... OK',
      processor: 'Begin teksverwerker... OK',
      storage: 'Kontroleer berging... OK',
      network: 'Netwerkkoppelvlak gereed... OK',
      ready: 'Stelsel gereed. Druk enige sleutel om voort te gaan.',
    },
    menu: {
      file: 'LÊER',
      edit: 'REDIGEER',
      view: 'AANSIG',
      network: 'NETWERK',
      storage: 'BERGING',
      power: 'KRAG',
      language: 'TAAL',
      settings: 'INSTELLINGS',
      music: 'MUSIEK',
    },
    file: { new: 'Nuut', open: 'Open', recent: 'Open Onlangs', save: 'Stoor', saveas: 'Stoor As' },
    edit: { undo: 'Ontdoen', redo: 'Herdoen', copy: 'Kopieer', paste: 'Plak', selectfont: 'Kies Font' },
    view: { increase: 'Vergroot Teksgrootte', decrease: 'Verklein Teksgrootte', customise: 'Pasmaak Kleure' },
    network: { wifi: 'Wi-Fi:', bluetooth: 'Bluetooth:', on: 'AAN', off: 'AF' },
    storage: { local: 'Plaaslike Berging', usb: 'USB-skyf (gesimuleer)', dropbox: '☁ Dropbox', gdrive: '☁ Google Drive', icloud: '☁ iCloud' },
    power: { update: 'Sagteware-opdatering', shutdown: 'Herbegin' },
    language: { select: 'Kies Taal', englishGB: 'Engels (VK)', englishUS: 'Engels (VSA)', afrikaans: 'Afrikaans' },
    status: { untitled: 'ONGETITELD.TXT', saved: 'GESTOOR', words: 'WOORDE', chars: 'KARAKTERS', battery: 'BATTERY:' },
    modals: {
      saveTitle: 'STOOR DOKUMENT', savePrompt: 'Voer lêernaam in...', saveButton: 'STOOR',
      openTitle: 'OPEN DOKUMENT', recentTitle: 'ONLANGSE DOKUMENTE',
      newTitle: 'NUWE DOKUMENT', newMessage1: 'Huidige dokument het ongestoorde veranderinge.', newMessage2: 'Stoor voor nuwe dokument geskep word?',
      saveAndNew: 'STOOR & NUUT', discard: 'VERWERP', cancel: 'KANSELLEER',
      noFiles: 'GEEN GESTOORDE DOKUMENTE', noRecent: 'GEEN ONLANGSE DOKUMENTE',
      colorsTitle: 'PASMAAK KLEURE', textColor: 'TEKSKLEUR:', textPresets: 'VOORAF INGESTELDE TEKSKLEURE:',
      bgColor: 'AGTERGROND:', bgPresets: 'VOORAF INGESTELDE AGTERGRONDE:', apply: 'TOEPAS', reset: 'HERSTEL NA VERSTEK',
      languageTitle: 'KIES TAAL',
    },
    help: { line1: 'Druk ESC om kieslys oop te maak', line2: 'Ctrl+S om te stoor | Ctrl+N vir nuwe lêer', line3: 'Ctrl+Z/R vir ontdoen/herdoen' },
    placeholder: 'Druk enige sleutel om te begin skryf...',
    shutdownConfirm: 'Herbegin Private Writer?',
    pin: {
      setupTitle: 'STEL PIN-SLOT OP',
      setupDesc: 'Beskerm jou skryfwerk met \'n PIN-kode',
      choose4: '4-SYFER PIN',
      choose6: '6-SYFER PIN',
      enterPin: 'Voer PIN in:',
      confirmPin: 'Bevestig PIN:',
      mismatch: 'PINs stem nie ooreen nie. Probeer weer.',
      set: 'STEL PIN',
      skip: 'SLAAN OOR',
      lockTitle: 'PRIVATE WRITER GESLUIT',
      lockDesc: 'Voer jou PIN in om te ontsluit',
      unlock: 'ONTSLUIT',
      incorrect: 'Verkeerde PIN. Probeer weer.',
      remove: 'Verwyder PIN-slot',
    },
  },
} as const;

export type LanguageStrings = typeof languages['en-GB'];

export function t(lang: string, path: string): string {
  const keys = path.split('.');
  let value: any = languages[lang as keyof typeof languages];
  if (!value) value = languages['en-GB'];
  for (const key of keys) {
    value = value?.[key];
    if (value === undefined) return path;
  }
  return value as string;
}
