import type { ChronicleDefinition } from './types';

export const CHRONICLES: ChronicleDefinition[] = [
  // ── Writing Consistency ─────────────────────────────────────────────
  {
    id: 'first-inkmark',
    name: 'The First Inkmark',
    category: 'consistency',
    description: 'Complete your first writing session',
    renownReward: 50,
    hidden: false,
    check: ctx => ctx.totalSessions >= 1,
  },
  {
    id: 'three-days-hence',
    name: 'Three Days Hence',
    category: 'consistency',
    description: 'Maintain a 3-day streak',
    renownReward: 100,
    hidden: false,
    check: ctx => ctx.streakDays >= 3,
  },
  {
    id: 'week-unbroken',
    name: 'The Week Unbroken',
    category: 'consistency',
    description: 'Maintain a 7-day streak',
    renownReward: 250,
    hidden: false,
    check: ctx => ctx.streakDays >= 7,
  },
  {
    id: 'fortnights-devotion',
    name: "A Fortnight's Devotion",
    category: 'consistency',
    description: 'Maintain a 14-day streak',
    renownReward: 500,
    hidden: false,
    check: ctx => ctx.streakDays >= 14,
  },
  {
    id: 'month-of-making',
    name: 'The Month of Making',
    category: 'consistency',
    description: 'Maintain a 30-day streak',
    renownReward: 1000,
    hidden: false,
    check: ctx => ctx.streakDays >= 30,
  },
  {
    id: 'creature-of-habit',
    name: 'Creature of Habit',
    category: 'consistency',
    description: 'Maintain a 60-day streak',
    renownReward: 400,
    hidden: false,
    check: ctx => ctx.streakDays >= 60,
  },

  // ── Word Count ─────────────────────────────────────────────────────
  {
    id: 'first-words-spoken',
    name: 'First Words Spoken',
    category: 'wordcount',
    description: 'Write 100 words total',
    renownReward: 50,
    hidden: false,
    check: ctx => ctx.totalWords >= 100,
  },
  {
    id: 'opening-chapter',
    name: 'The Opening Chapter',
    category: 'wordcount',
    description: 'Write 1,000 words total',
    renownReward: 100,
    hidden: false,
    check: ctx => ctx.totalWords >= 1000,
  },
  {
    id: 'into-the-story',
    name: 'Into the Story',
    category: 'wordcount',
    description: 'Write 10,000 words total',
    renownReward: 200,
    hidden: false,
    check: ctx => ctx.totalWords >= 10000,
  },
  {
    id: 'first-act',
    name: 'The First Act',
    category: 'wordcount',
    description: 'Write 25,000 words total',
    renownReward: 400,
    hidden: false,
    check: ctx => ctx.totalWords >= 25000,
  },
  {
    id: 'middle-distance',
    name: 'The Middle Distance',
    category: 'wordcount',
    description: 'Write 50,000 words total',
    renownReward: 600,
    hidden: false,
    check: ctx => ctx.totalWords >= 50000,
  },
  {
    id: 'nanowrimo-spirit',
    name: 'NaNoWriMo Spirit',
    category: 'wordcount',
    description: 'Write 50,000 words in a single month',
    renownReward: 800,
    hidden: false,
    check: ctx => ctx.monthWords >= 50000,
  },
  {
    id: 'full-manuscript',
    name: 'The Full Manuscript',
    category: 'wordcount',
    description: 'Write 80,000 words total',
    renownReward: 1000,
    hidden: false,
    check: ctx => ctx.totalWords >= 80000,
  },
  {
    id: 'prolific-voice',
    name: 'Prolific Voice',
    category: 'wordcount',
    description: 'Write 200,000 words total',
    renownReward: 2000,
    hidden: false,
    check: ctx => ctx.totalWords >= 200000,
  },

  // ── Session Performance ────────────────────────────────────────────
  {
    id: 'good-mornings-work',
    name: "A Good Morning's Work",
    category: 'session',
    description: 'Write 500 words in a single session',
    renownReward: 75,
    hidden: false,
    check: ctx => ctx.sessionWords >= 500,
  },
  {
    id: 'long-watch',
    name: 'The Long Watch',
    category: 'session',
    description: 'Write 1,000 words in a single session',
    renownReward: 150,
    hidden: false,
    check: ctx => ctx.sessionWords >= 1000,
  },
  {
    id: 'unbroken-flow',
    name: 'The Unbroken Flow',
    category: 'session',
    description: 'Write 2,000 words in a single session',
    renownReward: 300,
    hidden: false,
    check: ctx => ctx.sessionWords >= 2000,
  },
  {
    id: 'epic-session',
    name: 'The Epic Session',
    category: 'session',
    description: 'Write 5,000 words in a single session',
    renownReward: 750,
    hidden: false,
    check: ctx => ctx.sessionWords >= 5000,
  },
  {
    id: 'swift-of-quill',
    name: 'Swift of Quill',
    category: 'session',
    description: 'Complete a sprint with 100+ words in 15 minutes',
    renownReward: 100,
    hidden: false,
    check: ctx => ctx.sprintWords >= 100 && ctx.sprintMinutes <= 15,
  },
  {
    id: 'marathon-scribe',
    name: 'The Marathon Scribe',
    category: 'session',
    description: 'Write for 3+ hours in a single day',
    renownReward: 200,
    hidden: false,
    check: ctx => ctx.sessionMinutes >= 180,
  },

  // ── Project Milestones ─────────────────────────────────────────────
  {
    id: 'chapter-sung',
    name: 'A Chapter Sung',
    category: 'project',
    description: 'Complete your first chapter',
    renownReward: 100,
    hidden: false,
    check: ctx => ctx.totalChapters >= 1,
  },
  {
    id: 'ten-songs-recorded',
    name: 'Ten Songs Recorded',
    category: 'project',
    description: 'Complete 10 chapters across any projects',
    renownReward: 300,
    hidden: false,
    check: ctx => ctx.totalChapters >= 10,
  },
  {
    id: 'first-novel',
    name: 'The First Novel',
    category: 'project',
    description: 'Reach 80,000 words in a single project',
    renownReward: 2000,
    hidden: false,
    check: ctx => ctx.totalNovels >= 1,
  },
  {
    id: 'prolific-bard',
    name: 'The Prolific Bard',
    category: 'project',
    description: 'Complete 3 novels',
    renownReward: 3000,
    hidden: false,
    check: ctx => ctx.totalNovels >= 3,
  },
  {
    id: 'world-of-stories',
    name: 'A World of Stories',
    category: 'project',
    description: 'Have 5 active projects',
    renownReward: 200,
    hidden: false,
    check: ctx => ctx.totalProjects >= 5,
  },
  {
    id: 'keeper-of-many-tales',
    name: 'Keeper of Many Tales',
    category: 'project',
    description: 'Complete 100 chapters total',
    renownReward: 1000,
    hidden: false,
    check: ctx => ctx.totalChapters >= 100,
  },

  // ── Hidden ─────────────────────────────────────────────────────────
  {
    id: 'night-owl',
    name: 'Night Owl',
    category: 'hidden',
    description: 'Write between midnight and 4am',
    renownReward: 50,
    hidden: true,
    check: ctx => ctx.sessionHour >= 0 && ctx.sessionHour < 4,
  },
  {
    id: 'early-riser',
    name: 'The Early Riser',
    category: 'hidden',
    description: 'Write before 6am',
    renownReward: 50,
    hidden: true,
    check: ctx => ctx.sessionHour >= 4 && ctx.sessionHour < 6,
  },
  {
    id: 'hermits-path',
    name: "The Hermit's Path",
    category: 'hidden',
    description: 'Write offline for 7 consecutive sessions',
    renownReward: 150,
    hidden: true,
    check: ctx => ctx.offlineSessions >= 7,
  },
  {
    id: 'speed-demon',
    name: 'The Speed Demon',
    category: 'hidden',
    description: 'Reach 80 WPM in the Typing Challenge',
    renownReward: 100,
    hidden: true,
    check: ctx => ctx.wpmRecord >= 80,
  },
  {
    id: 'the-perfectionist',
    name: 'The Perfectionist',
    category: 'hidden',
    description: 'Save 10 version checkpoints',
    renownReward: 100,
    hidden: true,
    check: ctx => ctx.versionCheckpoints >= 10,
  },
  {
    id: 'character-obsessed',
    name: 'Character Obsessed',
    category: 'hidden',
    description: 'Create 20 character notes',
    renownReward: 150,
    hidden: true,
    check: ctx => ctx.characterNotes >= 20,
  },
];
